<?php

namespace Amplify\Widget\Components;

use Amplify\System\Cms\Models\Footer as FooterModel;
use Amplify\System\Cms\Models\Page;
use Amplify\Widget\Abstracts\BaseComponent;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Config;

/**
 * @class Footer
 */
class Footer extends BaseComponent
{
    /**
     * @var array
     */
    public $options;

    private ?Page $page;

    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        $this->options = Config::get('amplify.widget.'.__CLASS__, []);

        $this->page = store('dynamicPageModel', null);
    }

    /**
     * Whether the component should be rendered
     */
    public function shouldRender(): bool
    {
        if ($this->page instanceof Page) {
            return $this->page->has_footer;
        }

        return true;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        $contents = Cache::remember('site-footer', 86400, function () {
            return FooterModel::where(['is_enabled' => true])->pluck('content')->toArray();
        });

        $contents = implode("\n", $contents);

        $contents = str_replace('__year__', date('Y'), $contents);

        return view('widget::footer', [
            'content' => $contents,
        ]);
    }

    public function htmlAttributes(): string
    {
        $this->attributes = $this->attributes->class(['site-footer']);

        return parent::htmlAttributes(); // TODO: Change the autogenerated stub
    }
}
