<?php

namespace Amplify\Widget\Components\Product;

use Amplify\System\Backend\Models\Product;
use Amplify\System\Sayt\Classes\ItemRow;
use Amplify\Widget\Abstracts\BaseComponent;
use Closure;
use Illuminate\Contracts\View\View;

/**
 * @class MainImage
 */
class MainImage extends BaseComponent
{
    public function __construct(public ItemRow|Product $product , public string $seoPath = '', public bool $wrapLink = true)
    {
        parent::__construct();
    }

    /**
     * Whether the component should be rendered
     */
    public function shouldRender(): bool
    {
        return true;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('widget::product.main-image');
    }

    public function htmlAttributes(): string
    {
        $this->attributes = $this->attributes->merge([
            'class' => 'product-thumb',
            'href' => frontendSingleProductURL($this->product, $this->seoPath),
        ]);

        return parent::htmlAttributes(); // TODO: Change the autogenerated stub
    }
}
