<?php

namespace Amplify\Widget\Components\Product;

use Amplify\ErpApi\Facades\ErpApi;
use Amplify\System\Backend\Models\Product;
use Amplify\System\Sayt\Classes\ItemRow;
use Amplify\Widget\Abstracts\BaseComponent;
use Closure;
use Illuminate\Contracts\View\View;

/**
 * @class QuickAction
 */
class QuickAction extends BaseComponent
{
    public function __construct(public Product|ItemRow $product,
        public ?string $seoPath = '',
        public mixed $index = 1,
        public string $detailLabel = 'View Details',
        public string $cartLabel = 'Add To Cart',
        public array $extras = [])
    {
        parent::__construct();
    }

    /**
     * Whether the component should be rendered
     */
    public function shouldRender(): bool
    {
        return true;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        $cartData = [
            'id' => $this->product->Amplify_Id ?? $this->product->id,
            'code' => $this->product->Product_Code ?? $this->product->product_code,
            'available' => ErpApi::allowMultiWarehouse()
                ? $this->product->total_quantity_available ?? 1
                : $this->product->ERP->QuantityAvailable ?? 1,
            'customer_back_order' => ErpApi::getCustomerDetail()->BackorderCode == 'Y',
            'product_back_order' => boolval($this->product->allow_back_order ?? 0),
        ];

        if (isset($this->product->ERP?->WarehouseID)) {
            $defaultWarehouse = $this->product->ERP?->Warehouse;
        } else {
            $defaultWarehouse = customer_check()
                ? ErpApi::getCustomerDetail()->DefaultWarehouse
                : config('amplify.frontend.guest_checkout_warehouse');
        }

        return view('widget::product.quick-action', compact('cartData', 'defaultWarehouse'));
    }

    public function htmlAttributes(): string
    {
        $this->attributes = $this->attributes->class(['product-buttons']);

        return parent::htmlAttributes(); // TODO: Change the autogenerated stub
    }

    public function isMasterProduct($product)
    {
        if ($product instanceof ItemRow) {
            return $product->HasSku;
        }

        if ($product instanceof Product) {
            return ! empty($product->has_sku) && empty($product->parent_id);
        }

        return false;
    }
}
