<?php

namespace Amplify\Widget\Components\Amplify;

use Amplify\Widget\Abstracts\BaseComponent;
use Closure;
use Illuminate\Contracts\View\View;

/**
 * @class RightSidePanel
 */
class RightSidePanel extends BaseComponent
{
    /**
     * Whether the component should be rendered
     */
    public function shouldRender(): bool
    {
        $allowRightSidePanel = store('dynamicPageModel')?->has_right_sidebar ?? false;

        return config('amplify.frontend.right_sidebar', false) && $allowRightSidePanel;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {

        return view('widget::amplify.right-side-panel');
    }

    public function htmlAttributes(): string
    {
        $this->attributes = $this->attributes->class(['container']);

        return parent::htmlAttributes(); // TODO: Change the autogenerated stub
    }
}
